apiVersion: v1
kind: Service
metadata:
  name: nfs-nginx-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: nfs-nginx
  ports:
  - name: nfs-nginx
    port: 80
    targetPort: 80
    nodePort: 32134

