apiVersion: v1
kind: Service
metadata:
  name: nfs-anaconda3-svc
  namespace: anaconda3
spec:
  type: NodePort
  selector:
    app: nfs-anaconda3
  ports:
  - name: nfs-anaconda3
    port: 5000
    targetPort: 5000
    nodePort: 32150

