apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-anaconda3-chqsit
  namespace: anaconda3
spec:
  storageClassName: statefu-chqsit   #sc一定要指向上面创建的sc名称
  accessModes:
    - ReadWriteMany   #采用ReadWriteMany的访问模式
  resources:
    requests:
      storage: 5Gi    #请求5Gi的空间

