apiVersion: v1
kind: Pod
metadata:
  name: ollama-a100-template
  namespace: ai-training
  labels:
    app: training
    profile: ollama_a100
    owner: template
spec:
  restartPolicy: Never
  containers:
    - name: ollama
      image: ollama/ollama:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 11434
          name: ollama
      env:
        - name: OLLAMA_HOST
          value: "0.0.0.0:11434"
        - name: OLLAMA_MODELS
          value: "/root/.ollama"
        - name: OLLAMA_REPO_URL
          value: "http://nfs-ollamarepo-svc:11434"
      #resources:
      #  requests:
      #    cpu: "4"
      #    memory: "16Gi"
      #    nvidia.com/gpu: "1"
      #  limits:
      #    cpu: "8"
      #    memory: "32Gi"
      #    nvidia.com/gpu: "1"
#      volumeMounts:
#        - name: host-chqsit
#          mountPath: /root/.ollama
#  volumes:
#    - name: host-chqsit
#      hostPath:
#        path: /data/ollama/training

