apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: nfs-pythonai
  name: pythonai-sa
  namespace: ai-training

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pythonai-role
  namespace: ai-training
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pythonai-rolebinding
  namespace: ai-training
subjects:
  - kind: ServiceAccount
    name: pythonai-sa
    namespace: ai-training
roleRef:
  kind: Role
  name: pythonai-role
  apiGroup: rbac.authorization.k8s.io

