# Generated by Django 6.0.7 on 2026-08-21 01:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='budget',
            fields=[
                ('budgetid', models.AutoField(primary_key=True, serialize=False, verbose_name='预算序号')),
                ('budgetyear', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='预算年份')),
                ('budgetowner', models.CharField(blank=True, max_length=128, null=True, verbose_name='负责人')),
                ('budgetname', models.CharField(max_length=128, verbose_name='预算名称')),
                ('budgettype', models.CharField(choices=[('OPEX', 'OPEX'), ('CAPEX', 'CAPEX')], default='OPEX', max_length=6, verbose_name='预算类型')),
                ('budgetreminder', models.DateField(blank=True, null=True, verbose_name='预算使用提醒日期')),
                ('budgetplan', models.TextField(blank=True, default='暂时无计划', null=True, verbose_name='使用计划')),
                ('approval', models.BooleanField(default=False, verbose_name='预算核准')),
                ('budgetmoney', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name='预算金额(未税)')),
                ('longcontract', models.BooleanField(default=False, verbose_name='是否长期合同')),
                ('countdraw', models.BooleanField(default=False, verbose_name='是否计提')),
                ('countdrawmoney', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name='计提金额(未税)')),
            ],
            options={
                'verbose_name': '浏览预算数据',
                'verbose_name_plural': '预算数据',
                'db_table': 'budget',
            },
        ),
        migrations.CreateModel(
            name='PodUsageSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(choices=[('ollama_a100', 'A100'), ('ollama_h800', 'H800'), ('ollama_rtx5090', 'RTX5090')], max_length=32, verbose_name='硬件配置')),
                ('pod_name', models.CharField(max_length=128, verbose_name='容器名')),
                ('started_at', models.DateTimeField(verbose_name='开始时间')),
                ('stopped_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('elapsed_time', models.DurationField(blank=True, null=True, verbose_name='耗时')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pod_usage_sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Pod 使用记录',
                'verbose_name_plural': 'Pod 使用记录',
                'db_table': 'pod_usage_session',
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='PodUsageReport',
            fields=[
            ],
            options={
                'verbose_name': 'Pod 使用报表',
                'verbose_name_plural': 'Pod 使用报表',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.podusagesession',),
        ),
        migrations.CreateModel(
            name='pr',
            fields=[
                ('prid', models.AutoField(primary_key=True, serialize=False, verbose_name='采购序号')),
                ('prname', models.CharField(default='', max_length=128, verbose_name='采购名称')),
                ('po', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='PO号')),
                ('contract', models.BooleanField(default=False, verbose_name='合同完成')),
                ('contractbegin', models.DateField(blank=True, null=True, verbose_name='合同起始日期')),
                ('contractend', models.DateField(blank=True, null=True, verbose_name='合同终止日期')),
                ('contractmoney', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='本年合同金额(未税)')),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='税率')),
                ('checkaccept', models.BooleanField(default=False, verbose_name='合同验收')),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='验收比例')),
                ('paymentplan', models.TextField(blank=True, default='暂时无计划', null=True, verbose_name='使用计划')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='合同附件')),
                ('frombudget', models.ForeignKey(db_column='budgetid', on_delete=django.db.models.deletion.CASCADE, to='myapp.budget')),
            ],
            options={
                'verbose_name': '浏览采购数据',
                'verbose_name_plural': '采购数据',
                'db_table': 'pr',
            },
        ),
        migrations.CreateModel(
            name='TrainingContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(max_length=32, unique=True, verbose_name='槽位名')),
                ('profile', models.CharField(choices=[('ollama_a100', 'A100'), ('ollama_h800', 'H800'), ('ollama_rtx5090', 'RTX5090')], max_length=32, verbose_name='硬件配置')),
                ('pod_name', models.CharField(max_length=128, unique=True, verbose_name='容器名')),
                ('status', models.CharField(choices=[('free', 'Free'), ('starting', 'Starting'), ('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error')], default='free', max_length=16, verbose_name='状态')),
                ('host_port', models.PositiveIntegerField(blank=True, null=True, verbose_name='主机端口')),
                ('price_per_min', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='单价(元/分钟)')),
                ('token_nonce', models.CharField(blank=True, default='', max_length=64, verbose_name='连接签名随机值')),
                ('allocated_at', models.DateTimeField(blank=True, null=True, verbose_name='分配时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='启动时间')),
                ('stopped_at', models.DateTimeField(blank=True, null=True, verbose_name='停止时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_containers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '训练容器',
                'verbose_name_plural': '训练容器',
                'db_table': 'training_container',
            },
        ),
        migrations.AddField(
            model_name='podusagesession',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_sessions', to='myapp.trainingcontainer', verbose_name='训练容器'),
        ),
        migrations.CreateModel(
            name='training_platform',
            fields=[
            ],
            options={
                'verbose_name': '训练平台',
                'verbose_name_plural': '训练平台',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.trainingcontainer',),
        ),
    ]
