# Generated by Django 6.0.7 on 2026-08-07 15:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='budget',
            fields=[
                ('budgetid', models.AutoField(primary_key=True, serialize=False, verbose_name='预算序号')),
                ('budgetyear', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='预算年份')),
                ('budgetowner', models.CharField(blank=True, max_length=128, null=True, verbose_name='负责人')),
                ('budgetname', models.CharField(max_length=128, verbose_name='预算名称')),
                ('budgettype', models.CharField(choices=[('OPEX', 'OPEX'), ('CAPEX', 'CAPEX')], default='OPEX', max_length=6, verbose_name='预算类型')),
                ('budgetreminder', models.DateField(blank=True, null=True, verbose_name='预算使用提醒日期')),
                ('budgetplan', models.TextField(blank=True, default='暂时无计划', null=True, verbose_name='使用计划')),
                ('approval', models.BooleanField(default=False, verbose_name='预算核准')),
                ('budgetmoney', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name='预算金额(未税)')),
                ('longcontract', models.BooleanField(default=False, verbose_name='是否长期合同')),
                ('countdraw', models.BooleanField(default=False, verbose_name='是否计提')),
                ('countdrawmoney', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=16, null=True, verbose_name='计提金额(未税)')),
            ],
            options={
                'verbose_name': '浏览预算数据',
                'verbose_name_plural': '预算数据',
                'db_table': 'budget',
            },
        ),
        migrations.CreateModel(
            name='pr',
            fields=[
                ('prid', models.AutoField(primary_key=True, serialize=False, verbose_name='采购序号')),
                ('prname', models.CharField(default='', max_length=128, verbose_name='采购名称')),
                ('po', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='PO号')),
                ('contract', models.BooleanField(default=False, verbose_name='合同完成')),
                ('contractbegin', models.DateField(blank=True, null=True, verbose_name='合同起始日期')),
                ('contractend', models.DateField(blank=True, null=True, verbose_name='合同终止日期')),
                ('contractmoney', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='本年合同金额(未税)')),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='税率')),
                ('checkaccept', models.BooleanField(default=False, verbose_name='合同验收')),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='验收比例')),
                ('paymentplan', models.TextField(blank=True, default='暂时无计划', null=True, verbose_name='使用计划')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', verbose_name='合同附件')),
                ('frombudget', models.ForeignKey(db_column='budgetid', on_delete=django.db.models.deletion.CASCADE, to='myapp.budget')),
            ],
            options={
                'verbose_name': '浏览采购数据',
                'verbose_name_plural': '采购数据',
                'db_table': 'pr',
            },
        ),
        migrations.CreateModel(
            name='training_platform',
            fields=[
            ],
            options={
                'verbose_name': '训练平台',
                'verbose_name_plural': '训练平台',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.pr',),
        ),
    ]
