# Generated by Django 6.0.7 on 2026-08-20 08:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_podusagesession_elapsed_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodUsageReport',
            fields=[
            ],
            options={
                'verbose_name': 'Pod 使用报表',
                'verbose_name_plural': 'Pod 使用报表',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.podusagesession',),
        ),
    ]
